# Generated by Django 4.2.5 on 2024-05-25 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.CharField(max_length=100)),
                ("interval", models.IntegerField(default=1)),
                ("last_learned", models.DateField(default=datetime.date(1990, 1, 1))),
            ],
        ),
    ]
