# Generated by Django 4.2.5 on 2024-05-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_time", models.TimeField()),
                ("questions_per_day", models.IntegerField(default=20)),
            ],
        ),
    ]
